language: csharp
solution: BBK.App.sln
mono:
  - latest
install:
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm upgrade
  - dnu restore
script:
  - dnu build ./BBK.App.Tests/project.json
  - dnx -p ./BBK.App.Tests test